version: "3.3"
services:
  crashplan:
    build: .
    image: fredblgr/ubuntu-novnc:20.04-x86_64
    volumes:
        - /mnt/MargokPool/archive:/mnt/Archive:ro
    environment:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        USERNAME: user
    ports:
        - "6080:80"
    restart: unless-stopped
    privileged: true
    container_name: crashplan2
